name: main

on: [create, push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    container:
      image: pico:latest
      env:
        PICO_SDK_PATH: /etc/pico-sdk
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: bash build.bash --build

