name: main

on: [create, push, pull_request]
jobs:
  build:
    runs-on: [self-hosted, Linux, pico]
    env:
      BUILD_TYPE: Release
      PICO_SDK_PATH: /etc/pico-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Environment Monitor
      run: bash build.bash --build

    - name: Upload Environment Monitor
      uses: actions/upload-artifact@v3
      with:
          name: Environment Monitor firmware
          path: build/environment-monitor.uf2
