name: main

on: [create, push, pull_request]
jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    container:
      image: pico:latest
      env:
        BUILD_TYPE: Release
        PICO_SDK_PATH: /etc/pico-sdk

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: bash build.bash --build

